#!/usr/bin/env bash
# Idempotent installer for vreader-webdav-host.
# Refuses to run if placeholder sentinels haven't been replaced.

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_DIR="$HOME/.config/vreader-webdav-host"
INSTALL_DIR="$CONFIG_DIR/scripts"   # stable copy of scripts/ — survives repo move/delete
DATA_DIR="${VREADER_DATA_DIR:-$HOME/vreader-webdav-data}"
ICLOUD_DIR="${VREADER_ICLOUD_DIR:-$HOME/Library/Mobile Documents/com~apple~CloudDocs/VReaderBackups}"
PORT="${VREADER_PORT:-8080}"

# Helper: safe sed replacement — escape & and | for the LHS, escape | and \ for the RHS.
_sed_escape() { printf '%s' "$1" | sed -e 's/[\\|&]/\\&/g'; }

# 1. Preflight: always-required binaries.
for bin in htpasswd launchctl curl; do
  if ! command -v "$bin" >/dev/null 2>&1; then
    echo "ERROR: required binary '$bin' not found."
    case "$bin" in
      htpasswd) echo "Install Apache tools: brew install httpd" ;;
      launchctl|curl) echo "Should ship with macOS — investigate PATH." ;;
    esac
    exit 1
  fi
done

# 2. Install rclone if missing — only require Homebrew when we actually need to install.
if ! command -v rclone >/dev/null 2>&1; then
  if ! command -v brew >/dev/null 2>&1; then
    echo "ERROR: rclone is missing AND Homebrew is not installed."
    echo "  Either install Homebrew (https://brew.sh) and rerun setup.sh,"
    echo "  or install rclone manually: https://rclone.org/install/"
    exit 1
  fi
  echo "Installing rclone via Homebrew..."
  brew install rclone
fi
RCLONE_BIN="$(command -v rclone)"

# 3. Sentinel check — fail loudly if real htpasswd still has placeholder text.
if [[ -f "$CONFIG_DIR/htpasswd" ]] && grep -q "REPLACE_ME_PLACEHOLDER" "$CONFIG_DIR/htpasswd"; then
  echo "ERROR: $CONFIG_DIR/htpasswd still contains the placeholder sentinel."
  echo "Replace it: htpasswd -B -c $CONFIG_DIR/htpasswd youruser"
  exit 1
fi

# 4. Create dirs.
mkdir -p "$CONFIG_DIR" "$INSTALL_DIR" "$DATA_DIR" "$ICLOUD_DIR"

# 5. If no htpasswd exists, create one interactively.
if [[ ! -f "$CONFIG_DIR/htpasswd" ]]; then
  read -rp "WebDAV username: " webdav_user
  htpasswd -B -c "$CONFIG_DIR/htpasswd" "$webdav_user"
fi
# Always tighten perms — runs even on re-install with existing htpasswd.
chmod 600 "$CONFIG_DIR/htpasswd"

# 6. Copy scripts to a STABLE install dir so plists keep working if the repo moves.
cp "$REPO_DIR"/scripts/*.sh "$INSTALL_DIR/"
chmod +x "$INSTALL_DIR"/*.sh

# 7. Write env file the launchd-invoked sync script sources.
# Use printf %q to bash-escape values — paths with quotes / backticks / $()
# would otherwise break the file or execute when sourced later.
{
  echo "# Generated by setup.sh — do not edit by hand. Re-run setup.sh to regenerate."
  printf 'export VREADER_DATA_DIR=%q\n'   "$DATA_DIR"
  printf 'export VREADER_ICLOUD_DIR=%q\n' "$ICLOUD_DIR"
  printf 'export VREADER_PORT=%q\n'       "$PORT"
} > "$CONFIG_DIR/env"

# 8. Render launchd plists from templates with safe substitution.
ESC_RCLONE="$(_sed_escape "$RCLONE_BIN")"
ESC_DATA="$(_sed_escape "$DATA_DIR")"
ESC_ICLOUD="$(_sed_escape "$ICLOUD_DIR")"
ESC_HTPASSWD="$(_sed_escape "$CONFIG_DIR/htpasswd")"
ESC_INSTALL="$(_sed_escape "$INSTALL_DIR")"
ESC_PORT="$(_sed_escape "$PORT")"

for tmpl in "$REPO_DIR"/launchd/*.plist.template; do
  out="$CONFIG_DIR/$(basename "${tmpl%.template}")"
  sed \
    -e "s|\${RCLONE_PATH}|$ESC_RCLONE|g" \
    -e "s|\${DATA_DIR}|$ESC_DATA|g" \
    -e "s|\${ICLOUD_DIR}|$ESC_ICLOUD|g" \
    -e "s|\${HTPASSWD_PATH}|$ESC_HTPASSWD|g" \
    -e "s|\${PORT}|$ESC_PORT|g" \
    -e "s|\${INSTALL_DIR}|$ESC_INSTALL|g" \
    "$tmpl" > "$out"
done

# 9. Bootstrap launchd jobs (forces re-read of newly rendered plists).
"$INSTALL_DIR/start.sh"

# 10. Smoke test.
sleep 2
"$INSTALL_DIR/status.sh"

echo
echo "Setup complete."
echo "  WebDAV: http://127.0.0.1:$PORT — also reachable on LAN and Tailscale."
echo "  Data:   $DATA_DIR"
echo "  iCloud: $ICLOUD_DIR (hourly sync via com.vreader.icloud-sync)"
echo "  Logs:   /tmp/vreader-webdav.log, /tmp/vreader-icloud-sync.log"
